server:
  port: 8080
  servlet:
    context-path: /dog-market 
    
spring:
  datasource:
    url: jdbc:mariadb://dogmarket.cl7tswwcybq7.ap-northeast-2.rds.amazonaws.com:3306/dog-market
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: rootroot
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy ##default 여서 안넣어도 됨
    properties:
      hibernate:
        format_sql: true #To beautify or pretty print the SQL
     
